[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 main.py"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production.deploy]
startCommand = "python3 main.py"
